package fpermission

var CAMERA                 ,
WRITE_EXTERNAL_STORAGE ,
READ_EXTERNAL_STORAGE  ,
READ_PHONE_STATE       ,
READ_CALENDAR          ,
WRITE_CALENDAR         ,
READ_CONTACTS          ,
WRITE_CONTACTS         ,
GET_ACCOUNTS           ,
ACCESS_FINE_LOCATION   ,
ACCESS_COARSE_LOCATION ,
RECORD_AUDIO           ,
CALL_PHONE             ,
READ_CALL_LOG          ,
WRITE_CALL_LOG         ,
ADD_VOICEMAIL          ,
USE_SIP                ,
PROCESS_OUTGOING_CALLS ,
BODY_SENSORS           ,
SEND_SMS               ,
RECEIVE_SMS            ,
READ_SMS               ,
RECEIVE_WAP_PUSH       ,
RECEIVE_MMS            ="android.permission.CAMERA",
	"android.permission.WRITE_EXTERNAL_STORAGE",
	"android.permission.READ_EXTERNAL_STORAGE",
	"android.permission.READ_PHONE_STATE",
	"android.permission.READ_CALENDAR",
	"android.permission.WRITE_CALENDAR",
	"android.permission.READ_CONTACTS",
	"android.permission.WRITE_CONTACTS",
	"android.permission.GET_ACCOUNTS",
	"android.permission.ACCESS_FINE_LOCATION",
	"android.permission.ACCESS_COARSE_LOCATION",
	"android.permission.RECORD_AUDIO",
	"android.permission.CALL_PHONE",
	"android.permission.READ_CALL_LOG",
	"android.permission.WRITE_CALL_LOG",
	"android.permission.ADD_VOICEMAIL",
	"android.permission.USE_SIP",
	"android.permission.PROCESS_OUTGOING_CALLS",
	"android.permission.BODY_SENSORS",
	"android.permission.SEND_SMS",
	"android.permission.RECEIVE_SMS",
	"android.permission.READ_SMS",
	"android.permission.RECEIVE_WAP_PUSH",
	"android.permission.RECEIVE_MMS"